server.modules = (
    "mod_accesslog",
    "mod_alias",
    "mod_deflate",
    "mod_redirect",
    "mod_rewrite",
    "mod_indexfile",
)

server.document-root = "/var/www/localhost/htdocs"
server.bind = "0.0.0.0"
server.port = 80
server.indexfiles = ("index.html")

accesslog.filename = "/var/log/lighttpd/access.log"
server.errorlog = "/var/log/lighttpd/error.log"

# gzip/deflate compression (mod_deflate)
deflate.cache-dir = "/var/cache/lighttpd/deflate"

# SPA fallback: if file not found, serve /index.html (requires mod_rewrite)
url.rewrite-if-not-file = (
    ".*" => "/index.html",
)